name: Create Pull Request from Release to Main

on:
  push:
    branches:
      - release/*  # Trigger on push to any release branch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Create Pull Request from Release to Main
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main         # Target branch for the PR (main)
          head: ${{ github.ref }}  # Source branch for the PR (release/*)
          title: 'Release to Main'
          body: 'Automated pull request from release branch to main branch'
          labels: 'main'     # Add the 'main' label to the PR
