name: Deploy to sffnoobs environment on push to main

on:
  push:
    branches: [ main ]

jobs:
  Deploy-to-sffnoobs-environment:
    runs-on: ubuntu-latest
    environment: sffnoobs
    steps:
      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: 'Install Salesforce CLI'
        run: npm install @salesforce/cli --global

      - name: 'Install sfdx git delta'
        run: |
          echo Y | sfdx plugins:install sfdx-git-delta
          sfdx plugins

      - name: 'Create delta packages'
        run: | 
          mkdir -p changed-sources
          sf sgd source delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta --source CICD/force-app/main/default/
          echo "[INFO] Diff generated"

      - name: 'Authenticate Salesforce'
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" | tr -d '\r' > server.key
          sf org login jwt --username ${{ secrets.DEPLOYMENT_USER_NAME }} --jwt-key-file server.key --client-id ${{ secrets.CONSUMER_KEY }} --instance-url ${{ secrets.INSTANCE_URL }} --set-default

      - name: 'Deploy to environment with local tests'
        run: |
          if [ -d "changed-sources/force-app/main/default/" ] && [ "$(ls -A changed-sources/force-app/main/default/ 2>/dev/null)" ]; then
              echo "[INFO] Deploying delta changes..."
              sf project deploy start --source-dir changed-sources/force-app/main/default/ --test-level RunLocalTests
          else
              echo "[WARNING] No delta changes found. Deploying full source..."
              sf project deploy start --source-dir CICD/force-app/main/default/ --test-level RunLocalTests
          fi
