name: Deploy to sffnoobs environment on push to main

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:
    inputs:
      rollback:
        description: "Rollback to previous version"
        required: false
        default: "false"

jobs:
  Deploy-to-sffnoobs-environment:
    runs-on: ubuntu-latest
    environment: sffnoobs
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 'Install Salesforce CLI'
        run: npm install -g @salesforce/cli

      - name: 'Install sfdx git delta'
        run: |
          echo Y | sfdx plugins:install sfdx-git-delta
          sfdx plugins

      - name: 'Backup Before Merging'
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          ROLLBACK_BRANCH="rollback-$TIMESTAMP"

          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git checkout main
          git checkout -b $ROLLBACK_BRANCH
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $ROLLBACK_BRANCH
          
          echo "[INFO] Backup branch $ROLLBACK_BRANCH created."

      - name: 'Create delta packages'
        run: | 
          mkdir -p changed-sources
          sf sgd source delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta --source force-app/main/default/
          echo "[INFO] Diff generated"

      - name: 'Generate Destructive Changes'
        run: |
          mkdir -p destructive-changes

          sf sgd source delta --to "HEAD" --from "HEAD~1" --output destructive-changes/ --include-deleted

          if [ -f "destructive-changes/package.xml" ]; then
            mv destructive-changes/package.xml destructive-changes/destructiveChanges.xml
            echo "[INFO] Destructive changes detected."
          else
            echo "[WARNING] No destructive changes detected."
          fi

      - name: 'Authenticate Salesforce'
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" | tr -d '\r' > server.key
          sf org login jwt --username "${{ secrets.DEPLOYMENT_USER_NAME }}" --jwt-key-file server.key --client-id "${{ secrets.CONSUMER_KEY }}" --instance-url "${{ secrets.INSTANCE_URL }}" --set-default

      - name: 'Deploy Destructive Changes (Deletes)'
        if: success()
        run: |
          if [ -f "destructive-changes/destructiveChanges.xml" ]; then
            echo "[INFO] Deploying deletions..."
            sf project deploy start --manifest destructive-changes/destructiveChanges.xml --test-level NoTestRun
          else
            echo "[INFO] No deletions to deploy."
          fi

      - name: 'Deploy Additions/Modifications'
        if: success()
        run: |
          if [ -d "changed-sources/force-app/main/default" ] && [ "$(ls -A changed-sources/force-app/main/default 2>/dev/null)" ]; then
              echo "[INFO] Deploying delta changes..."
              sf project deploy start --source-dir changed-sources/force-app/main/default --test-level RunLocalTests
          else
              echo "[WARNING] No delta changes found. Deploying full source..."
              sf project deploy start --source-dir force-app/ --test-level RunLocalTests
          fi

  Rollback-Deployment:
    if: github.event.inputs.rollback == 'true'
    needs: [Deploy-to-sffnoobs-environment]
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout rollback branch'
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: 'Find latest rollback branch'
        run: |
          LATEST_ROLLBACK_BRANCH=$(git ls-remote --heads origin | awk -F'/' '{print $3}' | grep 'rollback-' | sort | tail -n 1)
          if [ -z "$LATEST_ROLLBACK_BRANCH" ]; then
            echo "No rollback branch found!"
            exit 1
          fi
          echo "LATEST_ROLLBACK_BRANCH=$LATEST_ROLLBACK_BRANCH" >> $GITHUB_ENV
          echo "[INFO] Found rollback branch: $LATEST_ROLLBACK_BRANCH"

      - name: 'Switch to latest rollback branch'
        run: |
          git fetch origin
          git checkout $LATEST_ROLLBACK_BRANCH

      - name: 'Authenticate Salesforce for Rollback'
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" | tr -d '\r' > server.key
          sf org login jwt --username "${{ secrets.DEPLOYMENT_USER_NAME }}" --jwt-key-file server.key --client-id "${{ secrets.CONSUMER_KEY }}" --instance-url "${{ secrets.INSTANCE_URL }}" --set-default

      - name: 'Rollback Deployment (Including Deletions)'
        run: |
          echo "[INFO] Rolling back to previous deployment..."
          sf project deploy start --source-dir force-app/main/default/ --test-level RunLocalTests
          echo "[INFO] Rollback complete."
