name: QA DEPLOY AND VALIDATION

on:
  push:
    branches: [ QA ]
  pull_request:
    branches: [ QA ]

  workflow_dispatch:
    inputs:
      rollback:
        description: "this is deploy and run test classes version"
        required: false
        default: "false"

jobs:
  Deploy-to-QA-environment:
    runs-on: ubuntu-latest
    environment: sffnoobs
    steps:
      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: 'Install Salesforce CLI'
        run: npm install @salesforce/cli --global

      - name: 'Install sfdx git delta'
        run: |
          echo Y | sfdx plugins:install sfdx-git-delta
          sfdx plugins

      - name: 'Authenticate Salesforce'
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" | tr -d '\r' > server.key
          sf org login jwt --username "${{ secrets.QA_ADMIN_USER }}" --jwt-key-file server.key --client-id "${{ secrets.QA_CONSUMER_KEY }}" --instance-url "${{ secrets.QA_INSTANCE_URL }}" --set-default

      - name: 'Create delta packages'
        run: | 
          mkdir -p changed-sources
          sf sgd source delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta --source force-app/main/default/
          echo "[INFO] Diff generated"

      - name: 'Deploy Entire PR with Extracted Test Classes'
        run: |
          sf project deploy start --source-dir force-app \
            --test-level RunSpecifiedTests --tests $TEST_CLASS_LIST --wait 10 --json > result.json || echo "DEPLOY_FAILED=true" >> $GITHUB_ENV

      - name: 'Debug JSON Output'
        run: |
          cat result.json

      - name: 'Install jq (For JSON Parsing)'
        run: sudo apt-get install -y jq

      - name: 'Parse Test Results'
        run: |
          TEST_RUN=$(jq -r '.result.details.runTestResult.numTestsRun // 0' result.json)
          CLASSES_DEPLOYED=$(jq -r '.result.details.componentSuccesses | length' result.json)
          echo "Tests Run: $TEST_RUN"
          echo "Total Classes Deployed: $CLASSES_DEPLOYED"
          if [[ "$TEST_RUN" -eq "0" ]]; then
            echo "No tests were executed! Failing the job."
            exit 1
          fi
