name: Create Consolidated PR for Release

on:
  workflow_dispatch:
    inputs:
      feature_branch_names:
        description: 'Comma-separated list of feature branch names (e.g., feature/v.33,feature/v.22)'
        required: true
      release_branch_name:
        description: 'Name of the release branch (e.g., release/v.34)'
        required: true

jobs:
  create_consolidated_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout the release branch
        run: |
          git fetch origin
          git checkout -b ${{ github.event.inputs.release_branch_name }} "origin/${{ github.event.inputs.release_branch_name }}"

      - name: Create and merge feature branches
        run: |
          FEATURE_BRANCHES="${{ github.event.inputs.feature_branch_names }}"
          RELEASE_BRANCH="${{ github.event.inputs.release_branch_name }}"
          TEMP_BRANCH="consolidated-pr-$(date +%s)"
          
          git checkout -b "$TEMP_BRANCH" "origin/$RELEASE_BRANCH"
          
          IFS=',' read -ra FEATURES <<< "$FEATURE_BRANCHES"
          for FEATURE in "${FEATURES[@]}"; do
            echo "Merging $FEATURE..."
            git merge "origin/$FEATURE" --no-edit || {
              echo "Merge conflict detected in $FEATURE";
              exit 1;
            }
          done
          
          git push origin "$TEMP_BRANCH"
        
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base "${{ github.event.inputs.release_branch_name }}" \
            --head "$TEMP_BRANCH" \
            --title "Consolidated PR: Merge all features into ${{ github.event.inputs.release_branch_name }}" \
            --body "This PR consolidates the following feature branches:\n${{ github.event.inputs.feature_branch_names }}"
