name: Create Consolidated PR for Release

on:
  workflow_dispatch:
    inputs:
      feature_branch_names:
        description: 'Comma-separated list of feature branch names (e.g., feature/v.33,feature/v.22)'
        required: true
      release_branch_name:
        description: 'Name of the release branch (e.g., release/v.34)'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  create_consolidated_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to access all branches

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check if release branch exists
        id: check_branch
        run: |
          if git ls-remote --exit-code --heads origin "${{ github.event.inputs.release_branch_name }}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create release branch if it doesn't exist
        if: steps.check_branch.outputs.exists == 'false'
        run: |
          git fetch origin main
          git checkout -b "${{ github.event.inputs.release_branch_name }}" origin/main
          git push origin "${{ github.event.inputs.release_branch_name }}"

      - name: Create consolidated branch and merge feature branches
        run: |
          git fetch --all

          IFS=',' read -ra FEATURES <<< "${{ github.event.inputs.feature_branch_names }}"
          RELEASE_BRANCH="${{ github.event.inputs.release_branch_name }}"
          TEMP_BRANCH="consolidated-pr-$(date +%s)"

          # Create temporary branch from release branch
          git checkout -b "$TEMP_BRANCH" "origin/$RELEASE_BRANCH"

          # Merge each feature branch
          for FEATURE in "${FEATURES[@]}"; do
            echo "Merging $FEATURE into $TEMP_BRANCH"
            git merge "origin/$FEATURE" --no-edit || echo "Merge conflict in $FEATURE — needs manual resolution"
          done

          git push origin "$TEMP_BRANCH"

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_BRANCH="${{ github.event.inputs.release_branch_name }}"
          TEMP_BRANCH="consolidated-pr-$(git log -1 --format=%ct)"

          gh pr create \
            --base "$RELEASE_BRANCH" \
            --head "$TEMP_BRANCH" \
            --title "Consolidated PR: Merge all features into $RELEASE_BRANCH" \
            --body "This PR consolidates multiple feature branches into $RELEASE_BRANCH:\n\n${{ github.event.inputs.feature_branch_names }}"
