name: Create Consolidated PR for Release

on:
  workflow_dispatch:
    inputs:
      feature_branch_names:
        description: 'Comma-separated list of feature branch names (e.g., feature/v.33,feature/v.22)'
        required: true
      release_branch_name:
        description: 'Name of the release branch (e.g., release/v.34)'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  create_consolidated_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for accessing all branches

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure release branch exists
        run: |
          RELEASE_BRANCH="${{ github.event.inputs.release_branch_name }}"
          git fetch origin $RELEASE_BRANCH || git fetch origin main && git checkout -b "$RELEASE_BRANCH" origin/main && git push origin "$RELEASE_BRANCH"

      - name: Create and push consolidated branch
        id: create_branch
        run: |
          FEATURE_BRANCHES="${{ github.event.inputs.feature_branch_names }}"
          RELEASE_BRANCH="${{ github.event.inputs.release_branch_name }}"
          TEMP_BRANCH="consolidated-pr-$(date +%s)"

          git fetch origin
          git checkout -b "$TEMP_BRANCH" "origin/$RELEASE_BRANCH"

          IFS=',' read -ra FEATURES <<< "$FEATURE_BRANCHES"
          for FEATURE in "${FEATURES[@]}"; do
            echo "Merging $FEATURE..."
            git merge "origin/$FEATURE" --no-edit || echo "Warning: Merge conflict in $FEATURE"
          done

          git push origin "$TEMP_BRANCH"
          echo "temp_branch=$TEMP_BRANCH" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base "${{ github.event.inputs.release_branch_name }}" \
            --head "${{ steps.create_branch.outputs.temp_branch }}" \
            --title "Consolidated PR: Merge all features into ${{ github.event.inputs.release_branch_name }}" \
            --body "This PR consolidates the following feature branches:\n${{ github.event.inputs.feature_branch_names }}"
